checks:
  php: true

build:
  environment:
    php:
      version: 7.4

  tests:
    override:
      - command: vendor/bin/phpunit --coverage-clover=coverage.xml
        coverage:
          file: coverage.xml
          format: clover

filter:
  paths:
    - 'src/*'
    - 'tests/*'

tools:
  php_code_coverage: true
