language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install -n --prefer-dist

script:
  - composer run-script test
  - composer run-script phpcs
